config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'home/index'
  resources :eventgroups
  resources :people do
    collection do
      post :import
    end
  end
  root "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/eventgroup.rb
class Eventgroup < ApplicationRecord
    validates :name, presence: true , uniqueness: true
    validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "should contain letters only" }

    has_many :memberships
    has_many :people, through: :memberships

    # Add a method to handle finding or creating an eventgroup by name
    def self.find_or_create_by_name(name)
      find_by(name: name) || create(name: name)
    end
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :person
    belongs_to :eventgroup
    validates_uniqueness_of :person_id, scope: :eventgroup_id
end

app/models/person.rb
class Person < ApplicationRecord
  validates :firstname, :lastname, :groupname, :role, presence: true      
  validates :firstname, :lastname, :groupname,  format: { with: /\A[a-zA-Z]+\z/, message: "should contain letters only" }
  ROLES = ['Organizer', 'Presenter', 'Participant']
  validates :role, inclusion: { in: ROLES, message: "valid values: orgainizer, presenter and participant"}
  has_many :memberships
  has_many :eventgroups, through: :memberships

  validate :unique_person_membership
  private

  def unique_person_membership
    # Check if there is any person with the same firstname, lastname, and groupname in the people table
    existing_person = Person.find_by(firstname: firstname, lastname: lastname, groupname: groupname)

    # If the person with the same attributes exists and it has a different ID (i.e., it's not the same person being updated),
    # add an error indicating that a person with the same firstname, lastname, and groupname already exists.
    if existing_person && existing_person.id != id
      errors.add(:base, "A person with the same first name, last name, and group name already exists")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/eventgroups_controller.rb
class EventgroupsController < ApplicationController
  before_action :set_eventgroup, only: %i[ show edit update destroy ]

  # GET /eventgroups or /eventgroups.json
  def index
    @eventgroups = Eventgroup.all
  end

  # GET /eventgroups/1 or /eventgroups/1.json
  def show 
    grpname = Eventgroup.find_by_id(params[:id]).name
  end

  # GET /eventgroups/new
  def new
    @eventgroup = Eventgroup.new
  end

  # GET /eventgroups/1/edit
  def edit
  end

  # POST /eventgroups or /eventgroups.json
  def create
    @eventgroup = Eventgroup.new(eventgroup_params)

    respond_to do |format|
      if @eventgroup.save
        format.html { redirect_to eventgroup_url(@eventgroup), notice: "Eventgroup was successfully created." }
        format.json { render :show, status: :created, location: @eventgroup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @eventgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventgroups/1 or /eventgroups/1.json
  def update
    respond_to do |format|
      if @eventgroup.update(eventgroup_params)
        format.html { redirect_to eventgroup_url(@eventgroup), notice: "Eventgroup was successfully updated." }
        format.json { render :show, status: :ok, location: @eventgroup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @eventgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventgroups/1 or /eventgroups/1.json
  def destroy
    #raise params.inspect
    @eventgroup.destroy

    respond_to do |format|
      format.html { redirect_to eventgroups_url, notice: "Eventgroup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eventgroup
      @eventgroup = Eventgroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def eventgroup_params
      params.require(:eventgroup).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.valid?
        checkgroupexists(@person.groupname, @person)        
        @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.valid?
        @person.update(person_params)
        @person.save!
        checkgroupexists(person_params["groupname"], @person) 
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    file = params[:file]
    return redirect_to people_path, notice: "CSV Files Only" unless file.content_type == "text/csv"
    import_service = CsvImportPeopleService.new

    theimport = import_service.importfile(file, method(:checkgroupexists))
    msg = ''
    theimport.each do |k, v|
      if !k.instance_of?(String)
        msg = msg + 'row - ' + k.to_s 
        msg = msg + ' has error ' + v.join(' ')
      else
        msg = msg + k 
        msg = msg + ' ' + v.to_s
      end
      msg = msg + '<br/>'
    end
    redirect_to people_path, notice: "import results .. <br/> #{msg}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:firstname, :lastname, :groupname, :role)
    end

    def checkgroupexists (groupname, person)
      eventgroup = Eventgroup.find_or_create_by(name: groupname)
      person.eventgroups << eventgroup
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventgroups_helper.rb
module EventgroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/eventgroups/_eventgroup.html.erb
<div id="<%= dom_id eventgroup %>">
  <p>
    <strong>Group Name:</strong>
    <%= eventgroup.name %> <b>Group Organizer(s): </b> <%= eventgroup.people.where(:role => 'Organizer').pluck(:firstname, :lastname).map{|x| x.join(' ')}.join(', ') %> 
  </p>
  <b>Others Group Members Include:</b><br/> 
  <% eventgroup.people.where.not(:role => 'Organizer').pluck(:firstname, :lastname, :role).map{|x| x.join(' ')}.each do |groupmember| %>
   <%= groupmember %><br/>
  <%end%>
</div>

app/views/eventgroups/_form.html.erb
<%= form_with(model: eventgroup) do |form| %>
  <% if eventgroup.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(eventgroup.errors.count, "error") %> prohibited this eventgroup from being saved:</h2>

      <ul>
        <% eventgroup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/eventgroups/edit.html.erb
<h1>Editing eventgroup</h1>

<%= render "form", eventgroup: @eventgroup %>

<br>

<div>
  <%= link_to "Show this eventgroup", @eventgroup %> |
  <%= link_to "Back to eventgroups", eventgroups_path %>
</div>

app/views/eventgroups/index.html.erb
<p style="color: green"><%= notice %></p>
<h5>Groups Listing</h5>
<br/>
<div id="eventgroups">
   <% @eventgroups.each do |eventgroup| %>
    <strong>Group Name:</strong><%= eventgroup.name %> <b>Group Organizer(s): </b> <%= eventgroup.people.where(:role => 'Organizer').pluck(:firstname, :lastname).map{|x| x.join(' ')}.join(', ') %> 
      <%= link_to "view group", eventgroup %> <br/><br/>
  <% end %>
</div>

<%= link_to "Create New Group", new_eventgroup_path %>

app/views/eventgroups/new.html.erb
<h1>New eventgroup</h1>

<%= render "form", eventgroup: @eventgroup %>

<br>

<div>
  <%= link_to "Back to eventgroups", eventgroups_path %>
</div>

app/views/eventgroups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @eventgroup %>

<div>
  <%= link_to "Edit this eventgroup", edit_eventgroup_path(@eventgroup) %> |
  <%= link_to "Back to eventgroups", eventgroups_path %>

  <%= button_to "Destroy this eventgroup", @eventgroup, method: :delete %>
</div>

app/views/home/index.html.erb
<h4>Welcome Demo App</h4>
<p>This app stores Users and the Groups they attend. Users have first names and last names. Groups have
a name. Users can attend multiple groups and have roles in each group. The roles are: Organizer,
Presenter, and Participant.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container-fluid">
        <%= render 'shared/top'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
  <div>
    <%= form.label :firstname, style: "display: block", class: "form-label" %>
    <%= form.text_field :firstname, {:class => 'form-control'} %>
  </div>
</div>
 <div class="input-group mb-3">
  <div>
    <%= form.label :lastname, style: "display: block", class: "form-label" %>
    <%= form.text_field :lastname, {:class => 'form-control'} %>
  </div>
</div>
 <div class="input-group mb-3">
  <div>
    <%= form.label :groupname, style: "display: block", class: "form-label" %>
    <%= form.text_field :groupname, {:class => 'form-control'} %>
  </div>
</div>
 <div class="input-group mb-3">
  <div>
    <%= form.label :role, style: "display: block", class: "form-label" %>
    <%= form.select :role, ['Organizer', 'Presenter', 'Participant'], {}, {:class => 'form-control'} %>
  </div>
</div>

  <div>
    <%= form.submit :class => "btn btn-success" %>
  </div>

<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Firstname:</strong>
    <%= person.firstname %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= person.lastname %>
  </p>

  <p>
    <strong>Groupname:</strong>
    <%= person.groupname %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= person.role %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= raw(flash[:notice])  %></p>
<h5>People Listing</h5>

<%=form_with url: import_people_path, method: :post do |form| %>
  <%= form.file_field :file, accept: ".csv", class: "form-control", :required => 'required'%>
  <br/>
  <%= form.button "import", class: "btn btn-primary" %>
<%end%>
<br/>
<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

app/views/shared/_top.html.erb
<% if user_signed_in? %> 
  <div> Welcome <%= current_user.email %> 
  <%= button_to "Sign out", destroy_user_session_path, class: 'btn btn-danger float-end', method: :delete %> 
</div>
<br/>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
    <li class="breadcrumb-item"><%= link_to "People", people_path%></li>
    <li class="breadcrumb-item"><%= link_to "Groups", eventgroups_path%></li>
  </ol>
</nav>
<%else%>
<%= link_to "Sign in", new_user_session_path,  data: { turbo: false }, class: "btn btn-primary float-end" %> 
<% end %>